package main

var Keywords = map[string]bool{
	"create":   true,
	"drop":     true,
	"if":       true,
	"exists":   true,
	"database": true,
	"table":    true,
	"primary":  true,
	"key":      true,
	"insert":   true,
	"into":     true,
	"values":   true,
	"from":     true,
	"select":   true,
	"set":      true,
	"update":   true,
	"delete":   true,
	"where":    true,
	"and":      true,
	"or":       true,
	"order":    true,
	"by":       true,
	"default":  true,
	"not":      true,
	"null":     true,
	"int":      true,
	"float":    true,
	"varchar":  true,
	"boolean":  true,
}
